#!/bin/sh /etc/rc.common
# wrt-sync: bring the local repository of releases up to date (r4s-release-pipeline
# D4) whenever the data disk is mounted; cron does it daily as well.
# shellcheck source=../../../../wrt-data/files/lib/functions/wrt-data.sh

# shellcheck disable=SC2034 # read by /etc/rc.common
START=99
# shellcheck disable=SC2034
USE_PROCD=1

start_service() {
	. /lib/functions/wrt-data.sh
	wrt_data_mounted || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/wrt-sync
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_restart_mount_trigger /mnt/data/repo
}
