#!/bin/sh /etc/rc.common
# Check the health of this boot once, after every other service has started.

# shellcheck disable=SC2034 # read by /etc/rc.common
START=99
# shellcheck disable=SC2034
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/wrt-healthcheck
	procd_close_instance
}
